menu:
  Home: /
  Archives: /archives
  About: /about
  Subscribe: /subscribe

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: undefinedblog

# google analytics
googleTrackId: UA-50332938-1
